### ISSUE TITLE
Armstrong Subero Book Programming with XC 8

### ISSUE THREAD

**Issue by johngmacdonald** [ArmstrongSubero/PIC16-Projects#2]
Need to know how to write Interrupts from his lessons in the book.

**Comment by johngmacdonald** [comment]
The book is using XC8 V 1.38 and MPLAX X v3.40, MPLAB is using XC8 V2.10 and MPLAB X  IDE V5.30
Just recently bought the book

**Comment by ArmstrongSubero** [comment]
Hi hope, its not too late, the interrupt format changed in that version of the compiler, you would have to do something similar like:

void __interrupt() isr(void)
{
    // Toggle led
    for(int x = 0; x <= 10; x++)
    {
        LATAbits.LATA1 = ~LATAbits.LATA1;
        __delay_ms(100);
    }
    
    // Clear interrupt flag
    INTCONbits.INTF = 0;
}

void main(void)
{
    // initialize the device
    SYSTEM_Initialize();

    // When using interrupts, you need to set the Global and Peripheral Interrupt Enable bits
    // Use the following macros to:

    // Enable the Global Interrupts
    //INTERRUPT_GlobalInterruptEnable();

    // Enable the Peripheral Interrupts
    //INTERRUPT_PeripheralInterruptEnable();

    // Disable the Global Interrupts
    //INTERRUPT_GlobalInterruptDisable();

    // Disable the Peripheral Interrupts
    //INTERRUPT_PeripheralInterruptDisable();
    
    
    // Set pin as input
    TRISAbits.TRISA2 = 1;
    ANSELAbits.ANSA2 = 0;
 
    // set the interrupt to rising edge
    OPTION_REGbits.INTEDG = 1;
     
    // clear the external interrupt flag 
    INTCONbits.INTF = 0;
    
    // enable external interrupts
    INTCONbits.INTE = 1;
    
    // enable global interrupts
    ei();
    

    while (1)
    {
        LATAbits.LATA1 = !LATAbits.LATA1;
        __delay_ms(1000);
    }
}
