### ISSUE TITLE
Not all code for the "Programming PIC microcontrollers with XC8"?

### ISSUE THREAD

**Issue by dietervansteenwegen** [ArmstrongSubero/PIC16-Projects#3]
Hi,

I was looking for the source code for the above mentioned book and expected it to be in this repo (as this repo is mentioned in the book...).

However (as just one example) chapter 6 has the "P01_CountdownTimer" project. The only  "P01" in the repository is "P01_Thermometer".

Where can I find the correct repository?

As a this is a book about coding, I kind of expect to be able to open the source code to make searching easier :).

Thanks.

**Comment by ArmstrongSubero** [comment]
The countdown timer project is there though this is not the repository for that book.
